# Generated by Django 4.2.3 on 2024-03-09 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hamayesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('date_of_hamayesh', django_jalali.db.models.jDateTimeField()),
                ('location', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='hamayeshat/')),
                ('status', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hamayeshat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantHamayesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=11)),
                ('full_name', models.CharField(max_length=255)),
                ('hamayesh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='hamayesh.hamayesh')),
            ],
        ),
    ]
