# Generated by Django 4.2.1 on 2024-03-05 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hamayesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('date_of_hamayesh', models.DateTimeField()),
                ('location', models.TextField()),
                ('status', models.CharField(choices=[('in_process', 'درحال اجرا'), ('not_started', 'شروع نشده'), ('end', 'پایان همایش')], max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hamayeshat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
