# Generated by Django 4.2.1 on 2024-03-08 05:33

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('hamayesh', '0003_participanthamayesh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamayesh',
            name='date_of_hamayesh',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
