# Generated by Django 4.2.3 on 2024-03-10 07:20

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
